version: '3'

services:

  mantis:
    image: "docker/mantis:1.2.19"
    ports:
      - 8080:80
    environment:
      - DB_HOST=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_NAME=
      - SMTP_HOST=
      - SMTP_USER=
      - SMPT_PASSWORD=
      - EMAIL_SENDER_ADDRESS=
      - EMAIL_WEBMASTER_ADDRESS=
      - EMAIL_RETURN_ADDRESS=
      - CRYPTO_SALT=
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 180s
